'use strict'

require("./h.js")
require("./hook.js")
require("./nested-properties.js")
require("./undefined-properties.js")
require("./keys.js")
require("./thunk.js")
require("./style.js")
require("./attributes")
require("./non-string.js")
require("./widget.js")
require("./patch.js")
require("./render.js")
require("./vnode.js")

require("../vdom/test/")
require("../vtree/test/")
require("../virtual-hyperscript/test/")
require("../vnode/test/")
